# Disclaimer

KDH Global ICT Intel Data is constructed from remote measurements based on the Internet Control Message Protocol (ICMP) echo request routine. As any remote measurement technology, KDH Global ICT Intel Data can only be an approximation of the local internet infrastructure and human experience of the internet on the ground. It is important to note that:


1. Our measurements only cover IP addresses in the IPv4 (IP version 4) space.
2. Any IP addresses that are not reachable by ICMP echo requests, are not included in our measurements.
3.The geolocation information for each of the individual IP addresses is based on data from Third Party providers and are updated on a monthly basis. The level of accuracy of the IP geolocation can vary across geographies and time and this can affect the accuracy of the KDH Global ICT Intel Data products. KASPR Datahaus PTY LTD makes no additional or express or implied warranties related to the accuracy of this location data across space and time. 
 

\paragraph{Assumptions} Furthermore, KDH data acquisition and data service provision relies on an assumed wider operating environment beyond the control or authority of KDH. Failure or interruption in any aspect of this operating environment can render KDH unable to acquire or provide data to clients in a timely manner, or at all. Assumed features of the operating environment include, but are not limited to:

 
1.  A functioning global internet layer, allowing the free flow of information packets, especially ICMP echo requests, across all networks and jurisdictions;
2.  Network neutrality such that KDH packets are managed in the internet layer in an equally expeditious manner to any other packet on the network;
3. A fully functional and operational commercial cloud infrastructure network, allowing remote server operation, interaction, data transmission between remote servers and storage locations, query at rest functions, and programmatic interaction and job activitation; and
4. A functioning remote authentication service and delivery mechanism to the client for final data transfer.
 

AS SUCH, KDH GLOBAL ICT INTEL DATA IS PROVIDED “AS IS” AND KASPR DATAHAUS PTY LTD MAKES NO ADDITIONAL OR EXPRESS OR IMPLIED WARRANTIES RELATING TO THE KASPR DATAHAUS DATA INCLUDING BY WAY OF EXAMPLE WARRANTIES OF MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE.

## Background Intellectual Property

In preparing these products KASPR Datahaus Pty Ltd asserts the ownership of the following methods and knowledge as background intellectual property in the field of measuring internet activity, latency and detection of anomalies, globally:
 
+ A method to scan, aggregate, analyse and visualise the number of latency (measured by ping response time) of very large numbers of internet-connected Internet Protocol addresses at a given location and time to produce internet measurement data;
+ Methods to carry out these functions from an online desktop device, remote server, or team of servers located in commercial cloud-based hosting platforms.
+ Methods to join internet measurement data with geo-location data for the purposes of re-aggregation, re-analysis, and visualisation;
+ A sampling method that aims at reducing the number of scanned IPs that are required to infer reliable measurements;
+ Methods to detect statistical anomalies and irregularities in internet measurement data, with tuneable thresholds; and
+ Methods to remotely deliver internet measurement data and derivative datasets to client end-points.
 