# License

KASPR Datahaus PTY LTD - Data License Agreement
 

A.	KASPR Datahaus PTY LTD (“Licensor”), 23 Banole Avenue, Prahran, Victoria, 3181,
               Australia is the creator and owner of the dataset (“KDH Data”) that you are licensing.
B.	You are purchasing the KDH Data through the licensor’s online shop (“Store”).
C.	The Licensor agrees to license the Data to you (“Licensee”) and you accept the grant of this license on the terms and conditions set out in this licence agreement (“Agreement”).
D. 	You accept the Agreement by clicking to agree or accepted where these options are presented to you, or actually using the KDH data. If you are accepting on behalf of your employer or other entity you warrant that you have full legal authority to bind your employer or entity to the Agreement and that you agree on behalf of your employer or other entity to the Agreement.
E. 	By clicking to agree or accepted where these options are presented to you warrant that you have read and understood the Agreement.



##	License:
KASPR Datahaus grants Licensee, its Affiliates and Nominated Consultants a worldwide, non-exclusive, non-sublicensable, non-transferable revocable license to access, copy and use the Data as further described herein. This license includes the right for Licensee, its Affiliates, and Nominated Consultants to:
      
+	import  any  Data  into  its  various  databases,  and  internally  redistribute  among  its departments  and  Affiliates  at  any  location  any  such  Data  or  databases  

+	use the Data for internal business or internal research purposes, 

+	create derivative works, including, but not limited to, incorporating the Data into its models and analyses, external products, applications, research publications and analyses based on the Data so long as only Insubstantial Amounts of the Data are exposed to third parties and such products are not competitive with the offering of the Data for sale.

Restrictions on use. Licensee agrees, except to the extent permitted by this Agreement or as required by law, not to and not to permit or authorise any third party to:

+	Decompile, disassemble, reverse-engineer or otherwise attempt to determine the source code or protocols or derive the executable, source or database code of the KDH Software; and agrees not to permit or authorize anyone else to do so. 

+	Not to sell, sublicense, assign, distribute, publish, transfer, disclose or otherwise make available the KDH Data in its current form or substantially similar form.

+	Permit users of any product or service that incorporates the KDH Data to download or export portions other than insubstantial amounts of the KDH Data.
 
+	Use the KDH Data in any manner or for any purpose that infringes, misappropriates, or otherwise violates any intellectual property right or other right of any person, or that violates any applicable law.

+	Copy, modify, translate or creative derivate works from the KDH Data; Disclose, sell, rent, lease, sublicense or otherwise transfer the KDH Data to third parties, provided that this shall not restrict Riskwolf from disclosing, selling, renting, leasing, licensing, assigning or otherwise transferring Outputs to any third party as provided in this agreement;

+	Use the KDH Data to reverse-engineer, or develop a software that has the same or similar function as the KDH software, or otherwise attempt to determine the underlying methods forming part of KDH Background IP, as used by KDH to generate the KDH Data  

**No-exclusivity.** The KDH Data is provided on a non-exclusive basis and licensee acknowledges that KDH may grant access to the KDH Data to third parties. For the avoidance of doubt, KDH is currently undertaking further research independently of this Agreement into the use of KDH Data and nothing in this Licence grants to licensee any license to the outcomes of such research or constrains KDH from exploiting or granting assignments or licenses to third parties to exploit the results of such research.

**Reservation of Rights.** Licensor reserves all rights not expressly granted to Licensee in this Agreement. Except for the limited rights and licenses expressly granted under this Agreement, nothing in this Agreement grants, by implication, waiver, estoppel, or otherwise, to Licensee or any third party any intellectual property rights or other right, title, or interest in or to the KDH Data. Without limiting the foregoing, Licensee shall not acquire any proprietary rights of the KDH Data.

##	Fees and Delivery.
Licensee shall pay the Fees, as calculated in the Store. Licensee is responsible for the timely payment of the Fees. If Licensee fails to make any payment when due, in addition to all other remedies that may be available: Licensor may prohibit access to the Data until all past due amounts have been paid, without incurring any obligation or liability to Licensee or any other person by reason of such prohibition of access to the Data.

*Taxes.* Licensee is responsible for all sales, use and excise taxes, and any other similar taxes, duties and charges of any kind imposed by any federal, state or local governmental or regulatory authority on the Fees, other than any taxes imposed on Licensor’s income.

*Delivery.* The KDH Data will be delivered to Licensee by Licensor through the Store. Licensor has no liability due to a delay in delivery or any temporary interruption in service of the Store.

##	Warranties
Licensee warrants and undertakes to Licensor that:
+	it has all rights necessary to grant all the rights that it purports to grant and perform all of its obligations under this Agreement, without the further consent or license of any third party;

+	to maintain adequate data security measures consistent with the ISO Standard and technology best practices to protect KDH Data from unauthorised disclosure or acquisition by an unauthorised person; it has obtained and will obtain and maintain, at its own cost, all consents, approvals, authorizations, licenses and/or permits, governmental or otherwise, required to perform its obligations under this Agreement; and

+	it shall remain in compliance with all laws, rules and regulations applicable to this Agreement, including without limitation all applicable data protection and data security laws, rules and regulations.

EXCEPT AS OTHERWISE SET FORTH IN THIS LICENSE (INCLUCING ANY SCHEDULE OR STATEMENT OF WORK), THE KDH DATA IS PROVIDED “AS IS” AND “AS AVAILABLE” BASED ON THE ASSUMPTIONS IDENTIFED IN THE PRODUCT DESCRIPTOR. KDH ACCEPTS NO RESPONSIBILITY FOR RELIANCE ON THE KDH DATA IN THE EVENT THE ASSUMPTIONS IDENTIFIED IN THE PRODUCT DESCRIPTOR ARE INCORRECT, INACCURATE OR DO NOT REFLECT REAL WORLD EVENTS OR OCCURANCES. KDH MAKES NO ADDITIONAL OR EXPRESS OR IMPLIED WARRANTIES RELATING TO THE KDH DATA INCLUDING BY WAY OF EXAMPLE WARRANTIES OF MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE.  

##	     Liability
In no event shall Licensor be liable for any indirect, incidental, consequential or punitive damages of any kind or nature whatsoever, including without limitation, lost revenues, savings or business and loss of profits, whether in an action based on contract, warranty, strict liability, tort (including, without limitation, negligence) or otherwise, even if such Party has been informed in advance of the possibility of such damages or such damages could have been reasonably foreseen by such Party. In no event will licensor’s aggregate liability arising out of or related to this agreement, under any legal theory including breach of contract, tort (including negligence), strict liability and otherwise, exceed the total fees paid by the licensee in the 12 months period preceding the event giving rise to the claim.   

##	Indemnity
Licensee shall fully indemnify, defend and hold harmless Licensor its affiliates, and their officers, directors, employees, agents, successors and assigns (KDH Indemnitees) from and against any and all third party claims, damages, liabilities, losses, and expenses (including any and all reasonable attorney fees, expenses and costs) (each a Claim) incurred by or asserted against any KDH Indemnitee of whatever kind or nature due to (a) a breach or alleged breach by licensee of any representation or warranty in the Agreement; and (b) a Claim related to the negligence or wilful misconduct of licensee, its employees, agents, or Personnel.

##	Licensee Covenants

Licensee represents and warrants that it has the full right, power and authority to enter into this Agreement and to perform its obligations hereunder; and that Licensee’s use of the Data and performance of this Agreement shall not violate, conflict with, or result in a material default under any other agreement, including confidentiality agreements between Licensee and third parties. Licensee covenants to maintain, hold and process the Data in compliance with all applicable laws. Licensee covenants it shall not attempt to reverse engineer, decompile, or otherwise re-identify the Data by using any method, including, but not limited to, merging external data with Data provided by Licensor. Licensee agrees to not (i) circumvent security features used to prevent or restrict access to or use the Shop or API, (ii) create user accounts by automated means or (iii) impersonate any person or entity.

##	Intellectual Property

Licensor is the owner of the Intellectual Property Rights in respect of the KDH Data. Nothing in this Agreement affects the ownership of any Intellectual Property Rights in the KDH Data with all such Intellectual Property Rights remaining with Licensor.     
Except for the right to access and use the KDH Data purchased at the Store, no license is granted to Licensee to the Licensor’s Background IP, or with respect to any other Intellectual Property Right owned or controlled by Licensor.

##	Termination

This Agreement may be terminated for cause forthwith on written notice:
(a)     by Licensor if Licensee has not remedied a material breach of the Agreement within 30 days of a notice requiring it to do so; or
(b)     by Licensor if Licensee ceases or threatens to cease to carry on its business, if a receiver, administrator or similar officer is appointed over all or any part of the assets or undertaking of the Licensee, if the Licensee makes any arrangement for the benefit of its creditors, if the Licensee goes into liquidation save for the purposes of a genuine amalgamation or reconstruction or any action is taken with respect to the Licensee in any jurisdiction which is analogous to any of the events referred to in this Section (b).

 This Agreement may be terminated without cause by Licensor on giving not less than one (1) month’s notice for termination 

##	Consequences of Termination or Expiry
Termination or expiry of this Agreement will not affect any rights of the Parties accrued to them up to the date of termination or expiry.

Return and Destruction of KDH Data. The Parties acknowledge that it is essential for Licensee to return or purge any and all KDH Data upon termination of this Agreement. In order to ensure that Licensee meets the requirements, Licensee shall:

+	At the instruction and request of Licensor, purge any and all KDH Data (but not any Input) in its possession or stored on any device, service or system, including any back-up copies, in accordance with KDH’s data purge instructions and mechanism, subject to any legal or regulatory restrictions imposed on Licensee to retain such content;

+	Allow Licensor access to the Licensee’s infrastructure in order to ensure the destruction of all KDH Data;

+	Collaborate with Licensor in order to ensure that all KDH Data is returned or destroyed in accordance with KDH’s instruction and data purge mechanism, including but not limited to providing written certification from a director of Licensee that Licensee has complied with this clause. This section shall survive any termination or expiration of this Agreement.


##	GENERAL

**Force Majeure.** Licensor will not be in breach of its contractual obligations in case of delay in performing, or failure to perform, its obligations under the Agreement  to the extent such delay or failure is caused by the occurrence of any contingency beyond the reasonable control, and without any fault, of such Party, which contingencies include but are not limited to acts of God, pandemics, epidemics, war, riot, power failures, internet disruption, fires, and floods (Force Majeure Event). For the avoidance of doubt, KDH measurement, aggregation, analysis and data delivery operation is hosted on Amazon Web Services (AWS) cloud infrastructure. Failure or interruption in any aspect of this AWS infrastructure also constitutes a Force Majeur Event because it is beyond reasonable control of Licensor. In any such event, the time limits for performance will be extended for a period of time equivalent to the time lost due to the Force Majeure Event. In order to avail itself of the relief provided in this Section 10.1., the affected Party shall act with due diligence to remedy the cause of, or to mitigate or overcome, such delay or failure.

**Assignment** Licensee shall not be entitled to assign any of its rights and/or obligations under this Agreement without the prior written consent of the other Licensor.

**No Partnership, Joint Venture or Agency.** The Agreement does not constitute either Party the agent of the other, or create a partnership, joint venture or similar relationship between the Parties, and no Party shall have the power to obligate or bind the other Party in any manner whatsoever (including the making of any representation or warranty, the assumption of any obligation or liability and the exercise of any right or power). The Parties shall act in all respects as independent contractors.

**Notices.** Any notice hereunder shall be in writing and shall be deemed to have been duly given: (i) 7 days after the date of mailing if sent by registered or certified mail, postage prepaid, with return receipt requested; (ii) when delivered if delivered personally or sent by express courier service;; or (iii) when transmitted via email, provided that the receiving Party acknowledges receipt by return email, and that the email clearly states in the subject line that it is intended to give notice hereunder. Any notice hereunder shall be sent to a Party at its address set forth in the first page of this Licence, and either Party may change such address by notice to the other Party.

**Enforceability.** Should any clause of the Agreement be found to be invalid or unenforceable, such clause (or part thereof) shall be deemed severed from the Agreement and the other clauses hereof shall remain in full force and effect as if the Agreement had been executed without the offending clause appearing. In such a case, the Parties shall negotiate in good faith and on a commercially reasonable efforts basis to agree alternative or amended valid, legal and enforceable clauses with the same economic effect as intended by the Parties hereto.

**Third Party Rights.** No provision of the Agreement is intended to create any rights in favour of any third party who is not a Party.

**Entire Agreement.** The Agreement constitute the entire agreement between the Parties with respect to the subject matter hereof and supersedes any other prior oral or written agreement regarding the subject matter hereof.

**Amendment.** The Agreement may be amended only by a written instrument duly signed by the Parties.

**Attribution.** Licensee must credit KASPR Datahaus PTY LTD if it publishes or creates content using the KDH Data.

**Governing Law and Jurisdiction.** The  Agreement and the respective rights and obligations of the Parties shall be governed by and construed in accordance with the laws of the State of Victoria, Australia . In the event of any dispute arising out of or in connection with this Agreement, the Parties shall first refer the dispute to proceedings under the ICC Mediation Rules. If the dispute has not been settled pursuant to the said Rules within 60 days following the filing of a Request for Mediation or within such other period as the Parties may agree in writing, such dispute shall thereafter be finally settled under the Rules of Arbitration of the International Chamber of Commerce by one or three arbitrators appointed in accordance with the said Rules of Arbitration. The place of mediation and arbitration shall be Melbourne, Australia, and the proceedings shall be in English. 

